<?php
/**
 *	Provides a dockblock for the minified classes file.
 *	
 * @package     Task Scheduler
 * @copyright   Copyright (c) 2014, <Michael Uno>
 * @author		Michael Uno
 * @authorurl	http://michaeluno.jp
 * @since		1.0.0
 * 
 */

// The minifier script includes this method to use the reflection class.
if ( ! class_exists( 'TaskScheduler_Registry_Base' ) ) {
	include_once( dirname( dirname( dirname( __FILE__ ) ) ) . '/task-scheduler.php' );
}

/**
 * Allows the minifier script to access plugin registries.
 */
class TaskScheduler_MinifiedVersionHeader extends TaskScheduler_Registry_Base {
	
	const Name			= 'Task Scheduler - Minified Classes';
	const Description	= 'Generated by the PHP Class Minifier';
	
}